/**
 * V1.2-6 / V1.2-7 (Feature 3 — HTML report). Pure renderer + file writer for
 * a self-contained, single-file HTML view of a `RunReport`.
 *
 * Why a separate module:
 *   - `report.json` is the canonical machine-readable artifact. The HTML is a
 *     presentation layer: optional (`--html` opt-in), schema-free, and never
 *     consumed back into the orchestrator. Keeping it isolated avoids
 *     entangling the JSON schema with display concerns.
 *
 * Design constraints (V1.2-PLAN.md Feature 3 + V1.2-6 / V1.2-7 briefs):
 *   - No new npm dependencies. Template literals, `escapeHtml`, and built-in
 *     `Intl.DateTimeFormat` only.
 *   - No JavaScript in the output. `<details>/<summary>` is the only
 *     disclosure primitive.
 *   - Self-contained: inline CSS, no external assets, opens in any browser.
 *   - Exit-reason text comes from `formatExitMessage` (single source of truth
 *     for human-readable exit text — shared with the CLI's stderr surface).
 *
 * V1.2-7 visual refinements (in order of effect on the layout):
 *   1. Section order under <main>: header → summary line → applied fixes →
 *      reverted fixes → baseline findings → check findings → footer. The two
 *      "what the run did" sections lead; informational sections follow.
 *   2. Summary line of metric pills (fixes applied / reverted / findings /
 *      LLM calls / optional capped-by-cap count) sits directly below the
 *      header for at-a-glance scanning.
 *   3. Check Findings are grouped first by checkId, then by file. Baseline
 *      findings keep per-file grouping (they are typically few and the
 *      category dimension is less useful there).
 *   4. Findings with a `proposedFix` render <details open>; prose-only
 *      findings (proposedFix === null, e.g. missing-test-coverage) render
 *      collapsed. This stops the dominant prose-only category from drowning
 *      out actionable fix candidates.
 *   5. `startedAt` / `finishedAt` render via `Intl.DateTimeFormat('en-GB')`
 *      with a "(local time)" suffix; `durationMs` renders as "X min Y sec"
 *      / "X sec" / "X ms" depending on magnitude.
 *   6. Inline CSS color palette is now documented and deliberate (green for
 *      applied, amber for reverted / capped, neutral gray for baseline, blue
 *      accent for the LLM-driven check section).
 *
 * Deviations from the V1.2-6 brief (preserved):
 *   1. Output path is `.sapui5-validator/report.html` (sits next to
 *      `report.json`, both written by the same `validatorDir`-based
 *      resolver). The brief's mention of `.sapui5-validator/last-run/` is
 *      based on the misconception that `report.json` lives under
 *      `last-run/`; it does not.
 *   2. `renderHtmlReport` takes a second `RenderHtmlReportOptions` argument
 *      so the title can show the project basename (RunReport carries no
 *      `projectRoot` field and bumping the schema is out of V1.2 scope).
 */

import { readFileSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import { formatExitMessage } from './messages.js';
import { validatorDir } from '../util/paths.js';
import { assertInsideProject } from '../util/containment.js';
import { SEMANTIC_CHECK_IDS } from '../types.js';
import type {
  AppliedFixRecord,
  CheckId,
  Finding,
  PostFixSuiteOutcome,
  ReportFileEntry,
  ReportGeneratedTest,
  RevertedFixRecord,
  RunReport,
} from '../types.js';

export const REPORT_HTML_FILE = 'report.html';

export interface RenderHtmlReportOptions {
  /**
   * Project root absolute path. Used solely to derive the human-readable
   * project name shown in the `<title>` and `<h1>` summary. Not embedded
   * elsewhere in the document.
   */
  readonly projectRoot: string;
  /**
   * Optional CLI version string (e.g. `"0.2.1"`). When present it is shown
   * in the footer ("Generated by sapui5-validate v<version>"). When omitted
   * the footer simply says "Generated by sapui5-validate". The writer
   * derives this from package.json; tests pass it explicitly so the unit
   * suite stays free of fs reads.
   */
  readonly version?: string;
}

/**
 * Render a complete HTML5 document for a `RunReport`. Pure function: no fs,
 * no env reads, no time-of-day dependencies. The output string starts with
 * `<!DOCTYPE html>` and ends with `</html>\n`.
 */
export function renderHtmlReport(
  report: RunReport,
  options: RenderHtmlReportOptions,
): string {
  const projectName = projectDisplayName(options.projectRoot);
  const titleText = `SAPUI5 Validator Report — ${projectName}, ${formatTimestamp(report.finishedAt)}`;
  const exitMessage = formatExitMessage(report.exitReason) ?? 'Success.';

  const summaryLine = renderSummaryLine(report);
  const appliedSection = renderAppliedFixesSection(report.files);
  const revertedSection = renderRevertedFixesSection(report.files);
  const baselineSection = renderBaselineFindingsSection(report.files);
  const checkSection = renderCheckFindingsSection(report.files);
  // COR-8: the primary outputs of a `generate` run (which tests passed /
  // quarantined) and the safety-critical post-fix-suite outcome of a `validate`
  // run. Each returns '' when not applicable and is filtered out below.
  const generatedSection = renderGeneratedTestsSection(report.generatedTests);
  const postFixSection = renderPostFixSuiteSection(report.postFixSuite);

  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="UTF-8">',
    `  <title>${escapeHtml(titleText)}</title>`,
    '  <style>',
    INLINE_CSS,
    '  </style>',
    '</head>',
    '<body>',
    '  <main>',
    renderHeader(report, projectName, exitMessage),
    summaryLine,
    appliedSection,
    revertedSection,
    generatedSection,
    postFixSection,
    baselineSection,
    checkSection,
    renderFooter(options.version),
    '  </main>',
    '</body>',
    '</html>',
  ]
    .filter((s) => s.length > 0)
    .join('\n') + '\n';
}

/**
 * Render and write `report.html` to `<projectRoot>/.sapui5-validator/report.html`.
 * Returns the absolute path of the file that was written. Mirrors
 * `writeReport`'s lifecycle: same parent directory, same trailing newline
 * convention. Callers are expected to handle / swallow failures the same way
 * they do for `writeReport` (the orchestrator treats both as non-blocking).
 */
export async function writeHtmlReport(
  projectRoot: string,
  report: RunReport,
): Promise<string> {
  const target = join(validatorDir(projectRoot), REPORT_HTML_FILE);
  // v0.8.1 V1: `.sapui5-validator/` can be a committed link out of the tree.
  await assertInsideProject(target, projectRoot);
  await mkdir(dirname(target), { recursive: true });
  const html = renderHtmlReport(report, {
    projectRoot,
    ...(CLI_VERSION !== undefined ? { version: CLI_VERSION } : {}),
  });
  await writeFile(target, html, 'utf8');
  return target;
}

// ---------------------------------------------------------------------------
// Internals

/**
 * Display names for the V1.2-7 group-by-checkId headings under the
 * "Check Findings" section. Keep this map in sync with `SemanticCheckId` in
 * src/types.ts — the unit test `'renders display name for every semantic
 * check id'` asserts on it.
 */
const CHECK_DISPLAY_NAMES: Readonly<Record<CheckId, string>> = {
  'no-direct-dom': 'No Direct DOM',
  'no-sync-odata': 'No Synchronous OData',
  'missing-teardown': 'Missing Teardown',
  'missing-i18n': 'Missing i18n',
  'manifest-component-drift': 'Manifest / Component Drift',
  'globals-in-views': 'Globals in Views',
  'missing-test-coverage': 'Missing Test Coverage',
  'baseline-ui5lint': 'Baseline — ui5lint',
  'baseline-eslint': 'Baseline — eslint',
  'baseline-karma': 'Baseline — karma',
  'baseline-unpreloaded-libs': 'Baseline — Unpreloaded Libraries',
};

function projectDisplayName(projectRoot: string): string {
  // Strip trailing path separators so `D:\` / `/foo/` produce a sensible name.
  const trimmed = projectRoot.replace(/[\\/]+$/, '');
  const name = basename(trimmed);
  return name === '' ? '(unnamed project)' : name;
}

function renderHeader(report: RunReport, projectName: string, exitMessage: string): string {
  const cappedLine = renderCappedLine(report);
  // COR-8: surface the detected sinon dialect on a `generate` run (absent on
  // validate and on early-return generate paths).
  const sinonLine =
    report.sinonDialect !== undefined
      ? `        <dt>Sinon dialect</dt><dd>${escapeHtml(report.sinonDialect)}</dd>`
      : '';
  return [
    '    <header>',
    '      <h1>SAPUI5 Validator Report</h1>',
    '      <dl class="summary">',
    `        <dt>Project</dt><dd>${escapeHtml(projectName)}</dd>`,
    `        <dt>Command</dt><dd><code>${escapeHtml(report.command)}</code></dd>`,
    `        <dt>Started</dt><dd>${escapeHtml(formatTimestamp(report.startedAt))}</dd>`,
    `        <dt>Finished</dt><dd>${escapeHtml(formatTimestamp(report.finishedAt))}</dd>`,
    `        <dt>Duration</dt><dd>${formatDuration(report.durationMs)}</dd>`,
    `        <dt>LLM calls</dt><dd>${report.llmCallCount} / ${report.llmCallBudget}</dd>`,
    `        <dt>Exit code</dt><dd>${report.exitCode}</dd>`,
    `        <dt>Exit reason</dt><dd>${escapeHtml(exitMessage)}</dd>`,
    cappedLine,
    sinonLine,
    '      </dl>',
    '    </header>',
  ]
    .filter((s) => s.length > 0)
    .join('\n');
}

/**
 * COR-8 — `generate`'s primary output: one row per generated test with its
 * status (passed / quarantined / no-output / skipped-baseline), the source it
 * was generated from, the `lint-only` verification marker when present, and the
 * quarantine reason when the test did not pass. Returns '' on a run with no
 * generated tests (every `validate` run) so the section is omitted.
 */
function renderGeneratedTestsSection(tests: readonly ReportGeneratedTest[]): string {
  if (tests.length === 0) return '';
  const items = tests.map(renderGeneratedTest).join('\n');
  return [
    '    <section class="generated-tests">',
    '      <h2>Generated Tests</h2>',
    '      <ul class="generated">',
    items,
    '      </ul>',
    '    </section>',
  ].join('\n');
}

function renderGeneratedTest(t: ReportGeneratedTest): string {
  const head = [
    `<span class="check-id">${escapeHtml(t.status)}</span>`,
    `<code>${escapeHtml(t.testFile)}</code>`,
    `<span class="source">from <code>${escapeHtml(t.sourceFile)}</code></span>`,
  ];
  if (t.verification !== undefined) {
    head.push(`<span class="source">[${escapeHtml(t.verification)}]</span>`);
  }
  const lines = [`          <li>${head.join(' ')}`];
  if (t.quarantineReason !== undefined) {
    lines.push(
      `            <div class="reason">${escapeHtml(t.quarantineReason.phase)}: ` +
        `${escapeHtml(t.quarantineReason.message)}</div>`,
    );
  }
  lines.push('          </li>');
  return lines.join('\n');
}

/**
 * COR-8 — the single post-fix karma suite gate outcome of a `validate` run that
 * applied at least one fix (absent otherwise). Surfaces the never-silent
 * partial-revert contract: a `revertFailedFiles` entry still carries an
 * unverified fix on disk.
 */
function renderPostFixSuiteSection(outcome: PostFixSuiteOutcome | undefined): string {
  if (outcome === undefined) return '';
  const lines = [
    '    <section class="post-fix-suite">',
    '      <h2>Post-fix Suite</h2>',
    `      <p>Status: <strong>${escapeHtml(outcome.status)}</strong></p>`,
  ];
  if (outcome.reason !== undefined && outcome.reason.length > 0) {
    lines.push(`      <p class="reason">${escapeHtml(outcome.reason)}</p>`);
  }
  appendFileList(lines, 'Reverted files', outcome.revertedFiles, false);
  appendFileList(lines, 'Revert FAILED — fix still on disk', outcome.revertFailedFiles, true);
  lines.push('    </section>');
  return lines.join('\n');
}

function appendFileList(
  lines: string[],
  label: string,
  files: readonly string[] | undefined,
  emphasise: boolean,
): void {
  if (files === undefined || files.length === 0) return;
  lines.push(`      <p${emphasise ? ' class="reason"' : ''}>${escapeHtml(label)}:</p>`);
  lines.push('      <ul class="fixes">');
  for (const f of files) lines.push(`        <li><code>${escapeHtml(f)}</code></li>`);
  lines.push('      </ul>');
}

function renderCappedLine(report: RunReport): string {
  const capped = report.cappedChecks;
  if (capped === undefined) return '';
  const entries = Object.entries(capped).filter(([, v]) => typeof v === 'number' && v > 0);
  if (entries.length === 0) return '';
  const parts = entries
    .map(([id, count]) => `${escapeHtml(id)}: ${count}`)
    .join(', ');
  return `        <dt>Capped checks</dt><dd>${parts}</dd>`;
}

/**
 * V1.2-7 — top-of-document scan band. Renders a single row of pill-shaped
 * metric spans. Static text, no JS, no chart: counts are aggregated from
 * `report.files` here so we don't depend on intermediate orchestrator state.
 */
function renderSummaryLine(report: RunReport): string {
  let applied = 0;
  let reverted = 0;
  let findings = 0;
  for (const f of report.files) {
    applied += f.appliedFixes.length;
    reverted += f.revertedFixes.length;
    findings += f.findings.length;
  }
  const callsText = `${report.llmCallCount}/${report.llmCallBudget} LLM calls used`;

  const pills: string[] = [
    `      <span class="metric metric-applied">${applied} ${applied === 1 ? 'fix' : 'fixes'} applied</span>`,
    `      <span class="metric metric-reverted">${reverted} reverted</span>`,
    `      <span class="metric metric-findings">${findings} ${findings === 1 ? 'finding' : 'findings'}</span>`,
    `      <span class="metric metric-info">${escapeHtml(callsText)}</span>`,
  ];

  const cappedTotal = totalCappedCount(report);
  if (cappedTotal > 0) {
    pills.push(
      `      <span class="metric metric-warning">${cappedTotal} capped by per-check-cap</span>`,
    );
  }

  return ['    <div class="summary-line">', ...pills, '    </div>'].join('\n');
}

function totalCappedCount(report: RunReport): number {
  const capped = report.cappedChecks;
  if (capped === undefined) return 0;
  let total = 0;
  for (const v of Object.values(capped)) {
    if (typeof v === 'number' && v > 0) total += v;
  }
  return total;
}

/**
 * Baseline section: per-file grouping (unchanged from V1.2-6 — baseline
 * findings are typically few; the category axis is less useful here).
 */
function renderBaselineFindingsSection(files: readonly ReportFileEntry[]): string {
  const filesWithFindings = files
    .map((f) => ({
      file: f.file,
      findings: f.findings.filter((finding) => finding.source === 'baseline'),
    }))
    .filter((f) => f.findings.length > 0);

  const body =
    filesWithFindings.length === 0
      ? '      <p class="empty">No baseline issues.</p>'
      : filesWithFindings
          .map((f) => renderFileFindings(f.file, f.findings))
          .join('\n');

  return [
    '    <section class="baseline-findings">',
    '      <h2>Baseline Findings (ui5lint, eslint, karma)</h2>',
    body,
    '    </section>',
  ].join('\n');
}

/**
 * V1.2-7 — Check Findings grouped first by checkId (in the declaration order
 * of `SEMANTIC_CHECK_IDS` for stable output), then by file within each
 * checkId group. The brief asked for "Missing Test Coverage (50 findings)"
 * sub-headings so the user can see the category distribution at a glance.
 */
function renderCheckFindingsSection(files: readonly ReportFileEntry[]): string {
  const groups = new Map<CheckId, Array<{ file: string; finding: Finding }>>();
  for (const fileEntry of files) {
    for (const finding of fileEntry.findings) {
      if (finding.source !== 'check') continue;
      const arr = groups.get(finding.checkId) ?? [];
      arr.push({ file: fileEntry.file, finding });
      groups.set(finding.checkId, arr);
    }
  }

  if (groups.size === 0) {
    return [
      '    <section class="check-findings">',
      '      <h2>Check Findings (LLM-driven)</h2>',
      '      <p class="empty">No check findings.</p>',
      '    </section>',
    ].join('\n');
  }

  // Stable order: follow SEMANTIC_CHECK_IDS declaration. Any unknown ids
  // (defensive — `CheckId` is closed, but the type system can't prevent a
  // stale schema) fall to the end in insertion order.
  const orderedIds: CheckId[] = [];
  for (const id of SEMANTIC_CHECK_IDS) {
    if (groups.has(id)) orderedIds.push(id);
  }
  for (const id of groups.keys()) {
    if (!orderedIds.includes(id)) orderedIds.push(id);
  }

  const groupBlocks = orderedIds.map((id) => {
    const entries = groups.get(id) ?? [];
    return renderCheckGroupByFile(id, entries);
  });

  return [
    '    <section class="check-findings">',
    '      <h2>Check Findings (LLM-driven)</h2>',
    ...groupBlocks,
    '    </section>',
  ].join('\n');
}

function renderCheckGroupByFile(
  checkId: CheckId,
  entries: ReadonlyArray<{ file: string; finding: Finding }>,
): string {
  // Sub-group entries by file while preserving first-seen file order so the
  // output is stable.
  const byFile = new Map<string, Finding[]>();
  for (const { file, finding } of entries) {
    const arr = byFile.get(file) ?? [];
    arr.push(finding);
    byFile.set(file, arr);
  }
  const count = entries.length;
  const displayName = CHECK_DISPLAY_NAMES[checkId] ?? checkId;
  const heading = `${displayName} (${count} ${count === 1 ? 'finding' : 'findings'})`;
  const fileBlocks: string[] = [];
  for (const [file, findings] of byFile) {
    fileBlocks.push(renderFileFindings(file, findings));
  }

  return [
    '      <div class="check-group">',
    `        <h3 class="check-group-heading">${escapeHtml(heading)} ` +
      `<span class="check-id">${escapeHtml(checkId)}</span></h3>`,
    ...fileBlocks,
    '      </div>',
  ].join('\n');
}

function renderFileFindings(file: string, findings: readonly Finding[]): string {
  const items = findings.map(renderFinding).join('\n');
  return [
    '      <div class="file-group">',
    `        <h4><code>${escapeHtml(file)}</code></h4>`,
    '        <ul class="findings">',
    items,
    '        </ul>',
    '      </div>',
  ].join('\n');
}

function renderFinding(finding: Finding): string {
  const lineText = finding.line !== undefined ? `:${finding.line}` : '';
  const checkBadge = `<span class="check-id">${escapeHtml(finding.checkId)}</span>`;
  // V1.9.8 Phase 2 — the served-from-cache honesty marker, rendered so an
  // HTML consumer sees which findings came from the cross-run cache rather
  // than a live LLM call on this run.
  const cachedBadge =
    finding.cached === true ? '<span class="check-id cached">cached</span>' : '';
  const header = `${checkBadge}${cachedBadge}<span class="line">${escapeHtml(lineText)}</span>`;
  const message = `<div class="message">${escapeHtml(finding.message)}</div>`;

  let detail = '';
  if (finding.proposedFix === null) {
    // Prose-only finding (no fix). V1.2-7: collapsed by default so a
    // missing-test-coverage flood doesn't drown out the actionable
    // sections. Explanation can be multi-line (e.g. raw lint stderr).
    detail = [
      '          <details>',
      '            <summary>Explanation</summary>',
      `            <pre><code>${escapeHtml(finding.explanation)}</code></pre>`,
      '          </details>',
    ].join('\n');
  } else {
    // Actionable: ships with a proposedFix. V1.2-7: open by default so the
    // fix candidate is immediately visible to a reviewer.
    detail = [
      '          <details open>',
      '            <summary>Proposed fix (new file content)</summary>',
      `            <pre><code>${escapeHtml(finding.proposedFix.newFileContent)}</code></pre>`,
      '          </details>',
    ].join('\n');
  }

  return [
    '          <li>',
    `            <div class="finding-head">${header}</div>`,
    `            ${message}`,
    detail,
    '          </li>',
  ].join('\n');
}

function renderAppliedFixesSection(files: readonly ReportFileEntry[]): string {
  const entries = files.filter((f) => f.appliedFixes.length > 0);
  const body =
    entries.length === 0
      ? '      <p class="empty">No fixes were applied.</p>'
      : entries.map(renderAppliedFileGroup).join('\n');
  return [
    '    <section class="applied-fixes">',
    '      <h2>Applied Fixes</h2>',
    body,
    '    </section>',
  ].join('\n');
}

function renderAppliedFileGroup(entry: ReportFileEntry): string {
  const items = entry.appliedFixes.map(renderAppliedFix).join('\n');
  return [
    '      <div class="file-group">',
    `        <h3><code>${escapeHtml(entry.file)}</code></h3>`,
    '        <ul class="fixes">',
    items,
    '        </ul>',
    '      </div>',
  ].join('\n');
}

function renderAppliedFix(record: AppliedFixRecord): string {
  return (
    '          <li>' +
    `<span class="check-id">${escapeHtml(record.checkId)}</span>` +
    ` <span class="source">[${escapeHtml(record.source)}]</span>` +
    '</li>'
  );
}

function renderRevertedFixesSection(files: readonly ReportFileEntry[]): string {
  const entries = files.filter((f) => f.revertedFixes.length > 0);
  const body =
    entries.length === 0
      ? '      <p class="empty">No fixes were reverted.</p>'
      : entries.map(renderRevertedFileGroup).join('\n');
  return [
    '    <section class="reverted-fixes">',
    '      <h2>Reverted Fixes</h2>',
    body,
    '    </section>',
  ].join('\n');
}

function renderRevertedFileGroup(entry: ReportFileEntry): string {
  const items = entry.revertedFixes.map(renderRevertedFix).join('\n');
  return [
    '      <div class="file-group">',
    `        <h3><code>${escapeHtml(entry.file)}</code></h3>`,
    '        <ul class="fixes">',
    items,
    '        </ul>',
    '      </div>',
  ].join('\n');
}

function renderRevertedFix(record: RevertedFixRecord): string {
  return [
    '          <li>',
    `            <span class="check-id">${escapeHtml(record.checkId)}</span>` +
      ` <span class="source">[${escapeHtml(record.source)}]</span>`,
    `            <div class="reason">${escapeHtml(record.reason)}</div>`,
    '          </li>',
  ].join('\n');
}

function renderFooter(version: string | undefined): string {
  const versionText =
    version !== undefined && version.length > 0
      ? `sapui5-validate v${escapeHtml(version)}`
      : 'sapui5-validate';
  return [
    '    <footer>',
    `      <p>Generated by ${versionText}. Audit log at <code>.sapui5-validator/last-run/</code> (or <code>.sapui5-validator/runs/&lt;timestamp&gt;/</code> when run with <code>--keep-history</code>).</p>`,
    '    </footer>',
  ].join('\n');
}

/**
 * V1.2-7 — human-readable timestamp. en-GB is chosen for the unambiguous
 * "day-month-year, 24-hour" form (no AM/PM, no MM/DD/YY ambiguity). The
 * formatter uses the system's local timezone: the goal is readability for
 * whoever opens the report on their machine, not cross-machine
 * determinism. Tests assert on date-portion substrings ("May 2026") that
 * survive any reasonable timezone offset for the sample timestamps.
 *
 * Exported for unit testing. Falls back to the raw input if the value is
 * not a valid date.
 */
export function formatTimestamp(iso: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return iso;
  const fmt = new Intl.DateTimeFormat('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  });
  return `${fmt.format(date)} (local time)`;
}

/**
 * V1.2-7 — duration in "X min Y sec" / "X sec" / "X ms" form. Sub-second
 * shows ms (rare for real runs but covers the unit test scenarios);
 * sub-minute shows whole seconds; longer runs show minutes + remainder
 * seconds. No singular/plural inflection on units — the brief used fixed
 * "min" / "sec" labels.
 */
export function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms} ms`;
  const totalSeconds = Math.round(ms / 1000);
  if (totalSeconds < 60) return `${totalSeconds} sec`;
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds - minutes * 60;
  return `${minutes} min ${seconds} sec`;
}

// HTML5 escaping covers the five characters that can break out of element
// content / attribute context. Apostrophes are escaped to keep the output
// safe when (later) embedded inside double-quoted attributes; over-escaping
// is harmless and keeps a single helper for both contexts.
const HTML_ESCAPE: Readonly<Record<string, string>> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

export function escapeHtml(input: string): string {
  return input.replace(/[&<>"']/g, (ch) => HTML_ESCAPE[ch] ?? ch);
}

// Read once at module load — same pattern as cli.ts. Failures fall through
// to `undefined` so the renderer gracefully omits the version.
const CLI_VERSION: string | undefined = readCliVersion();

function readCliVersion(): string | undefined {
  try {
    const pkgUrl = new URL('../../package.json', import.meta.url);
    const raw = readFileSync(pkgUrl, 'utf8');
    const parsed = JSON.parse(raw) as { version?: unknown };
    return typeof parsed.version === 'string' ? parsed.version : undefined;
  } catch {
    return undefined;
  }
}

/*
 * V1.2-7 inline CSS palette — chosen deliberately. Future visual changes
 * should preserve the semantics rather than swap colors without rationale.
 *
 *   Green   (#10b981 / #047857 / #ecfdf5):   applied fixes, "positive" outcome
 *   Amber   (#f59e0b / #92400e / #fef3c7):   reverted fixes, capped categories
 *                                             — "attention but not critical"
 *   Red     (reserved, currently only #8a1f1f for the reverted-fixes h2 and
 *            the .reason text):              hard failure / error narrative
 *   Blue    (#2845b2 / #1e3a8a / #eef2ff):   info / check-id badges, LLM
 *                                             callouts ("informational accent")
 *   Gray    (#6b7280 / #1f2937 / #f3f4f6):   neutral / baseline findings,
 *                                             generic counts
 *
 * The 0.9-0.95 background lightness on metric pills keeps the foreground
 * color WCAG AA against the page background. The reverted-fixes left
 * border was #d97706 (arbitrary V1.2-6 orange); it is now #f59e0b —
 * intentionally on the amber scale to match the metric pill family.
 */
const INLINE_CSS = `
    :root {
      color-scheme: light;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      padding: 2rem 1rem;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
        "Helvetica Neue", Arial, sans-serif;
      color: #1c1c1c;
      background: #f7f7f8;
      line-height: 1.45;
    }
    main {
      max-width: 1000px;
      margin: 0 auto;
      background: #ffffff;
      border: 1px solid #e3e3e6;
      border-radius: 6px;
      padding: 1.5rem 2rem 2rem;
    }
    h1 {
      margin: 0 0 0.5rem;
      font-size: 1.5rem;
    }
    h2 {
      margin: 1.75rem 0 0.75rem;
      font-size: 1.15rem;
      padding-bottom: 0.25rem;
      border-bottom: 1px solid #e3e3e6;
    }
    h3 {
      margin: 1rem 0 0.5rem;
      font-size: 0.95rem;
      font-weight: 600;
    }
    h4 {
      margin: 0.75rem 0 0.4rem;
      font-size: 0.9rem;
      font-weight: 600;
      color: #444;
    }
    code, pre {
      font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace;
      font-size: 0.85rem;
    }
    pre {
      background: #f3f3f5;
      border: 1px solid #e3e3e6;
      border-radius: 4px;
      padding: 0.5rem 0.75rem;
      overflow-x: auto;
      white-space: pre-wrap;
      word-break: break-word;
    }
    dl.summary {
      display: grid;
      grid-template-columns: max-content 1fr;
      gap: 0.25rem 1rem;
      margin: 0.5rem 0 0;
    }
    dl.summary dt {
      font-weight: 600;
      color: #555;
    }
    dl.summary dd {
      margin: 0;
    }
    /* V1.2-7 summary line — pill row of headline counts. */
    .summary-line {
      display: flex;
      flex-wrap: wrap;
      gap: 0.5rem;
      margin: 1.25rem 0 0.5rem;
    }
    .summary-line .metric {
      font-size: 0.9rem;
      font-weight: 600;
      padding: 0.4rem 0.75rem;
      border-radius: 5px;
      background: #f3f4f6;
      color: #1f2937;
    }
    .summary-line .metric-applied { background: #ecfdf5; color: #047857; }
    .summary-line .metric-reverted { background: #fef3c7; color: #92400e; }
    .summary-line .metric-findings { background: #f3f4f6; color: #1f2937; }
    .summary-line .metric-info { background: #eef2ff; color: #1e3a8a; }
    .summary-line .metric-warning { background: #fef3c7; color: #92400e; }
    section {
      margin-top: 0.5rem;
    }
    .check-group {
      margin: 0.5rem 0 1rem;
      padding-left: 0.75rem;
      border-left: 3px solid #2845b2; /* info-blue: LLM-driven category */
    }
    .check-group-heading {
      display: flex;
      align-items: center;
      gap: 0.5rem;
    }
    .file-group {
      margin-left: 0.5rem;
      padding-left: 0.75rem;
      border-left: 2px solid #e3e3e6;
    }
    /* Baseline findings (pre-existing lint/test failures): neutral gray
       to differentiate visually from LLM-driven check findings. */
    .baseline-findings .file-group {
      border-left-color: #6b7280;
    }
    /* Applied fixes: subtle green stripe. */
    .applied-fixes .file-group {
      border-left-color: #10b981;
    }
    ul.findings, ul.fixes {
      list-style: none;
      padding-left: 0;
      margin: 0.25rem 0 0.75rem;
    }
    ul.findings > li, ul.fixes > li {
      margin: 0.5rem 0;
      padding: 0.5rem 0.75rem;
      background: #fafafa;
      border: 1px solid #ececef;
      border-radius: 4px;
    }
    .check-id {
      font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
      font-size: 0.8rem;
      background: #eef2ff;
      color: #2845b2;
      padding: 0.1rem 0.4rem;
      border-radius: 3px;
    }
    .source {
      color: #777;
      font-size: 0.8rem;
    }
    .line {
      color: #777;
      font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
      font-size: 0.8rem;
      margin-left: 0.4rem;
    }
    .message {
      margin: 0.35rem 0;
    }
    .reason {
      margin-top: 0.25rem;
      color: #8a1f1f;
      font-size: 0.9rem;
    }
    .empty {
      color: #777;
      font-style: italic;
      margin: 0.25rem 0 0.75rem;
    }
    /* Reverted fixes: amber attention (was an arbitrary #d97706 in V1.2-6). */
    .reverted-fixes h2 {
      color: #8a1f1f;
    }
    .reverted-fixes .file-group {
      border-left-color: #f59e0b;
    }
    details summary {
      cursor: pointer;
      color: #2845b2;
      font-size: 0.85rem;
    }
    footer {
      margin-top: 2rem;
      padding-top: 0.75rem;
      border-top: 1px solid #e3e3e6;
      color: #777;
      font-size: 0.85rem;
    }
`;
