/**
 * V1.2-6 / V1.2-7 (Feature 3 — HTML report). Unit coverage for
 * `renderHtmlReport` (pure renderer), `writeHtmlReport` (file writer),
 * `formatTimestamp` and `formatDuration` (humanization helpers).
 *
 * Pattern mirrors test/unit/report.test.ts:
 *   - `renderHtmlReport` is a pure function. We assert on substrings of
 *     the returned document rather than parsing it as DOM — keeps the test
 *     dependency-free and the assertions readable diff-by-diff.
 *   - `writeHtmlReport` gets one tmpdir test (path resolves under
 *     `.sapui5-validator/`, file is on disk, content matches the renderer).
 *   - Timestamp assertions only check date-portion substrings ("May 2026")
 *     that survive any reasonable timezone offset; the formatter renders in
 *     the system's local zone by design.
 */

import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, test } from 'vitest';
import { createEmptyReport } from '../../src/output/report.js';
import {
  REPORT_HTML_FILE,
  escapeHtml,
  formatDuration,
  formatTimestamp,
  renderHtmlReport,
  writeHtmlReport,
} from '../../src/output/html.js';
import type { ReportFileEntry, RunReport } from '../../src/types.js';

const PROJECT_ROOT = '/tmp/some-project';
const RENDER_OPTS = { projectRoot: PROJECT_ROOT, version: '0.2.1' };

function baseReport(overrides: Partial<RunReport> = {}): RunReport {
  const started = new Date('2026-05-18T10:00:00Z');
  const empty = createEmptyReport('validate', started, 50);
  return { ...empty, ...overrides };
}

describe('renderHtmlReport — document skeleton', () => {
  test('renders a complete HTML5 document from a minimal report (empty findings)', () => {
    const html = renderHtmlReport(baseReport(), RENDER_OPTS);
    // HTML5 doctype + lang.
    expect(html.startsWith('<!DOCTYPE html>')).toBe(true);
    expect(html).toContain('<html lang="en">');
    // Required head elements.
    expect(html).toContain('<meta charset="UTF-8">');
    expect(html).toContain('<title>');
    expect(html).toContain('<style>');
    // Semantic body shell.
    expect(html).toContain('<header>');
    expect(html).toContain('<footer>');
    // Always-present section headings — even on an empty report, sections
    // render with explicit "None"/"No" messages rather than disappearing.
    expect(html).toContain('Baseline Findings (ui5lint, eslint, karma)');
    expect(html).toContain('Check Findings (LLM-driven)');
    expect(html).toContain('Applied Fixes');
    expect(html).toContain('Reverted Fixes');
    // Document terminates cleanly with a trailing newline.
    expect(html.endsWith('</html>\n')).toBe(true);
  });

  test('title shows project basename and humanized finishedAt, not the full project path', () => {
    const html = renderHtmlReport(baseReport(), { projectRoot: '/home/me/cap_try' });
    expect(html).toContain('<title>SAPUI5 Validator Report — cap_try, ');
    expect(html).not.toContain('/home/me/cap_try');
    // Humanized timestamp leaks into the title; raw ISO does not.
    expect(html).not.toContain('2026-05-18T10:00:00.000Z');
  });

  test('project basename falls back to "(unnamed project)" when projectRoot has no basename', () => {
    // POSIX root path — basename('/') === '' once trailing separators are stripped.
    const html = renderHtmlReport(baseReport(), { projectRoot: '/' });
    expect(html).toContain('(unnamed project)');
  });

  test('footer includes the CLI version when provided', () => {
    const html = renderHtmlReport(baseReport(), {
      projectRoot: PROJECT_ROOT,
      version: '0.2.1',
    });
    expect(html).toContain('sapui5-validate v0.2.1');
  });

  test('footer omits the version chunk when not provided', () => {
    const html = renderHtmlReport(baseReport(), { projectRoot: PROJECT_ROOT });
    expect(html).toMatch(/Generated by sapui5-validate\./);
    expect(html).not.toMatch(/sapui5-validate v/);
  });

  test('footer references the audit log location (and the --keep-history alternate)', () => {
    const html = renderHtmlReport(baseReport(), RENDER_OPTS);
    expect(html).toContain('.sapui5-validator/last-run/');
    expect(html).toContain('--keep-history');
  });

  test('V1.2-7 section order: summary line → applied → reverted → baseline → check → footer', () => {
    const html = renderHtmlReport(baseReport(), RENDER_OPTS);
    const summaryIdx = html.indexOf('class="summary-line"');
    const appliedIdx = html.indexOf('Applied Fixes');
    const revertedIdx = html.indexOf('Reverted Fixes');
    const baselineIdx = html.indexOf('Baseline Findings');
    const checkIdx = html.indexOf('Check Findings');
    const footerIdx = html.indexOf('<footer>');
    expect(summaryIdx).toBeGreaterThan(-1);
    expect(summaryIdx).toBeLessThan(appliedIdx);
    expect(appliedIdx).toBeLessThan(revertedIdx);
    expect(revertedIdx).toBeLessThan(baselineIdx);
    expect(baselineIdx).toBeLessThan(checkIdx);
    expect(checkIdx).toBeLessThan(footerIdx);
  });
});

describe('renderHtmlReport — generate output (COR-8)', () => {
  test('renders generatedTests, postFixSuite, and the sinon dialect', () => {
    const report = baseReport({
      command: 'generate',
      sinonDialect: 'sap-bundled',
      generatedTests: [
        {
          sourceFile: 'webapp/controller/Main.controller.js',
          testFile: 'webapp/test/unit/controller/Main.controller.qunit.js',
          status: 'passed',
        },
        {
          sourceFile: 'webapp/controller/Bad.controller.js',
          testFile: 'webapp/test/_failing/Bad.controller.qunit.js',
          status: 'quarantined',
          quarantineReason: { phase: 'refinement', message: 'karma module-load failure' },
        },
      ],
      postFixSuite: {
        status: 'failed',
        reason: 'the qunit suite went red after the fix phase',
        revertedFiles: ['webapp/controller/X.controller.js'],
        revertFailedFiles: ['webapp/controller/Y.controller.js'],
      },
    });
    const html = renderHtmlReport(report, RENDER_OPTS);

    // Generated tests: both entries + the quarantine reason are visible.
    expect(html).toContain('Generated Tests');
    expect(html).toContain('webapp/test/unit/controller/Main.controller.qunit.js');
    expect(html).toContain('webapp/test/_failing/Bad.controller.qunit.js');
    expect(html).toContain('quarantined');
    expect(html).toContain('karma module-load failure');

    // Post-fix suite outcome + the never-silent revert-failed signal.
    expect(html).toContain('Post-fix Suite');
    expect(html).toContain('the qunit suite went red after the fix phase');
    expect(html).toContain('Revert FAILED');
    expect(html).toContain('webapp/controller/Y.controller.js');

    // Sinon dialect.
    expect(html).toContain('Sinon dialect');
    expect(html).toContain('sap-bundled');
  });

  test('escapes generated-test + post-fix fields', () => {
    const report = baseReport({
      command: 'generate',
      generatedTests: [
        {
          sourceFile: 'webapp/<x>.js',
          testFile: 'webapp/test/<evil>.qunit.js',
          status: 'no-output',
        },
      ],
      postFixSuite: { status: 'not-run', reason: 'no qunit tests in scope <none>' },
    });
    const html = renderHtmlReport(report, RENDER_OPTS);
    expect(html).toContain('webapp/test/&lt;evil&gt;.qunit.js');
    expect(html).toContain('no qunit tests in scope &lt;none&gt;');
    expect(html).not.toContain('<evil>');
  });

  test('omits the generate sections on a validate run with no generated output', () => {
    const html = renderHtmlReport(baseReport(), RENDER_OPTS);
    expect(html).not.toContain('Generated Tests');
    expect(html).not.toContain('Post-fix Suite');
    expect(html).not.toContain('Sinon dialect');
    // The document still terminates cleanly.
    expect(html.endsWith('</html>\n')).toBe(true);
  });
});

describe('renderHtmlReport — header summary', () => {
  test('summary block exposes command, dates, duration, llm-call ratio, exit code, exit reason', () => {
    const report = baseReport({
      command: 'validate',
      startedAt: '2026-05-18T10:00:00.000Z',
      finishedAt: '2026-05-18T10:00:45.000Z',
      durationMs: 45000,
      llmCallCount: 12,
      llmCallBudget: 50,
      exitCode: 0,
      exitReason: { kind: 'success' },
    });
    const html = renderHtmlReport(report, RENDER_OPTS);
    expect(html).toContain('<code>validate</code>');
    // Humanized timestamps: month name + year appear; raw ISO does not.
    expect(html).toContain('May 2026');
    expect(html).not.toContain('2026-05-18T10:00:00.000Z');
    expect(html).not.toContain('2026-05-18T10:00:45.000Z');
    // 45000 ms → 45 sec
    expect(html).toContain('45 sec');
    expect(html).toContain('12 / 50');
    // success → formatExitMessage returns null → fallback "Success." text.
    expect(html).toContain('Success.');
  });

  test('exit reason uses the V1.2-4 user-friendly text from formatExitMessage', () => {
    const html = renderHtmlReport(
      baseReport({
        exitReason: { kind: 'budget-exhausted', calls: 17 },
        exitCode: 1,
      }),
      RENDER_OPTS,
    );
    // Substrings asserted by test/unit/error-messages.test.ts — proves the
    // HTML inherits whatever phrasing formatExitMessage produces.
    expect(html).toContain('LLM call budget reached after 17 calls');
    expect(html).toContain('--max-llm-calls');
    expect(html).toContain('--per-check-cap');
  });

  test('cappedChecks summary appears in header when V1.2-2 cap blocked calls', () => {
    const report = baseReport({
      cappedChecks: {
        'missing-teardown': 2,
        'no-direct-dom': 1,
      },
    });
    const html = renderHtmlReport(report, RENDER_OPTS);
    expect(html).toContain('Capped checks');
    expect(html).toContain('missing-teardown: 2');
    expect(html).toContain('no-direct-dom: 1');
  });

  test('cappedChecks summary is omitted when the cap never bit', () => {
    // Field absent (default).
    const noField = renderHtmlReport(baseReport(), RENDER_OPTS);
    expect(noField).not.toContain('Capped checks');
    // Field present but empty (all counts 0 — unlikely in practice but
    // guard against it).
    const emptyField = renderHtmlReport(
      baseReport({ cappedChecks: { 'no-direct-dom': 0 } }),
      RENDER_OPTS,
    );
    expect(emptyField).not.toContain('Capped checks');
  });
});

describe('renderHtmlReport — V1.2-7 summary line', () => {
  function fileWith(overrides: Partial<ReportFileEntry>): ReportFileEntry {
    return {
      file: 'webapp/x.js',
      findings: [],
      appliedFixes: [],
      revertedFixes: [],
      ...overrides,
    };
  }

  test('shows zero counts for an empty report', () => {
    const html = renderHtmlReport(baseReport(), RENDER_OPTS);
    expect(html).toContain('class="summary-line"');
    expect(html).toContain('0 fixes applied');
    expect(html).toContain('0 reverted');
    expect(html).toContain('0 findings');
    expect(html).toContain('0/50 LLM calls used');
  });

  test('aggregates counts across all files', () => {
    const html = renderHtmlReport(
      baseReport({
        llmCallCount: 17,
        llmCallBudget: 80,
        files: [
          fileWith({
            file: 'webapp/A.js',
            findings: [
              {
                checkId: 'no-direct-dom',
                file: 'webapp/A.js',
                message: 'x',
                source: 'check',
                proposedFix: { newFileContent: '' },
              },
              {
                checkId: 'no-direct-dom',
                file: 'webapp/A.js',
                message: 'y',
                source: 'check',
                proposedFix: { newFileContent: '' },
              },
            ],
            appliedFixes: [
              { checkId: 'no-direct-dom', source: 'check' },
              { checkId: 'no-direct-dom', source: 'check' },
              { checkId: 'no-direct-dom', source: 'check' },
            ],
            revertedFixes: [
              { checkId: 'no-direct-dom', source: 'check', reason: 'r' },
            ],
          }),
          fileWith({
            file: 'webapp/B.js',
            findings: [
              {
                checkId: 'missing-i18n',
                file: 'webapp/B.js',
                message: 'z',
                source: 'check',
                proposedFix: null,
                explanation: 'why',
              },
            ],
            appliedFixes: [{ checkId: 'missing-i18n', source: 'check' }],
            revertedFixes: [],
          }),
        ],
      }),
      RENDER_OPTS,
    );
    expect(html).toContain('4 fixes applied');
    expect(html).toContain('1 reverted');
    expect(html).toContain('3 findings');
    expect(html).toContain('17/80 LLM calls used');
  });

  test('singular wording for counts of exactly 1', () => {
    const html = renderHtmlReport(
      baseReport({
        files: [
          {
            file: 'webapp/A.js',
            findings: [
              {
                checkId: 'no-direct-dom',
                file: 'webapp/A.js',
                message: 'x',
                source: 'check',
                proposedFix: null,
                explanation: 'why',
              },
            ],
            appliedFixes: [{ checkId: 'no-direct-dom', source: 'check' }],
            revertedFixes: [],
          },
        ],
      }),
      RENDER_OPTS,
    );
    expect(html).toContain('1 fix applied');
    expect(html).toContain('1 finding');
    // Plural unchanged for 0.
    expect(html).toContain('0 reverted');
  });

  test('capped-by-cap pill appears only when cappedChecks has nonzero entries', () => {
    const withCap = renderHtmlReport(
      baseReport({
        cappedChecks: { 'missing-test-coverage': 5, 'no-direct-dom': 2 },
      }),
      RENDER_OPTS,
    );
    expect(withCap).toContain('class="metric metric-warning"');
    expect(withCap).toContain('7 capped by per-check-cap');

    const noCap = renderHtmlReport(baseReport(), RENDER_OPTS);
    expect(noCap).not.toContain('capped by per-check-cap');
  });
});

describe('renderHtmlReport — findings sections', () => {
  function fileEntry(overrides: Partial<ReportFileEntry>): ReportFileEntry {
    return {
      file: 'webapp/controller/Main.controller.js',
      findings: [],
      appliedFixes: [],
      revertedFixes: [],
      ...overrides,
    };
  }

  test('one file with one check finding renders under "Check Findings"', () => {
    const html = renderHtmlReport(
      baseReport({
        files: [
          fileEntry({
            findings: [
              {
                checkId: 'no-direct-dom',
                file: 'webapp/controller/Main.controller.js',
                line: 14,
                message: 'document.querySelector is forbidden',
                source: 'check',
                proposedFix: { newFileContent: '// fixed\n' },
              },
            ],
          }),
        ],
      }),
      RENDER_OPTS,
    );
    // File name appears once under check-findings, never under baseline.
    expect(html).toContain('<code>webapp/controller/Main.controller.js</code>');
    expect(html).toContain('no-direct-dom');
    expect(html).toContain(':14');
    expect(html).toContain('document.querySelector is forbidden');
    // The proposed fix is rendered inside a <details open> block (V1.2-7).
    expect(html).toContain('<details open>');
    expect(html).toContain('<summary>Proposed fix (new file content)</summary>');
    expect(html).toContain('// fixed');
    // Baseline section still says "No baseline issues."
    expect(html).toContain('No baseline issues.');
  });

  test('one baseline finding with multi-line stderr renders under "Baseline Findings"', () => {
    const html = renderHtmlReport(
      baseReport({
        files: [
          fileEntry({
            file: 'webapp/controller/Broken.controller.js',
            findings: [
              {
                checkId: 'baseline-ui5lint',
                file: 'webapp/controller/Broken.controller.js',
                message: 'ui5lint reported errors',
                source: 'baseline',
                proposedFix: null,
                explanation:
                  'webapp/controller/Broken.controller.js:13:7 - error\n  unused variable',
              },
            ],
          }),
        ],
      }),
      RENDER_OPTS,
    );
    expect(html).toContain('baseline-ui5lint');
    expect(html).toContain('Broken.controller.js');
    expect(html).toContain('<summary>Explanation</summary>');
    // Multi-line text inside <pre><code>: both lines must survive.
    expect(html).toContain('unused variable');
    // No "check finding" leakage into the wrong section.
    expect(html).toContain('No check findings.');
  });

  test('findings are split by source: same file with both kinds appears in BOTH sections', () => {
    const html = renderHtmlReport(
      baseReport({
        files: [
          fileEntry({
            findings: [
              {
                checkId: 'baseline-ui5lint',
                file: 'webapp/controller/Main.controller.js',
                message: 'baseline issue',
                source: 'baseline',
                proposedFix: null,
                explanation: 'ui5lint stderr text',
              },
              {
                checkId: 'no-direct-dom',
                file: 'webapp/controller/Main.controller.js',
                message: 'semantic issue',
                source: 'check',
                proposedFix: { newFileContent: '// fix\n' },
              },
            ],
          }),
        ],
      }),
      RENDER_OPTS,
    );
    // V1.2-7 order: baseline still precedes check in the body.
    const baselineIdx = html.indexOf('Baseline Findings');
    const checkIdx = html.indexOf('Check Findings');
    expect(baselineIdx).toBeGreaterThan(-1);
    expect(checkIdx).toBeGreaterThan(baselineIdx);
    // The file path appears under each section (≥2 occurrences across the
    // document).
    const count = html.split('webapp/controller/Main.controller.js').length - 1;
    expect(count).toBeGreaterThanOrEqual(2);
  });
});

describe('renderHtmlReport — V1.2-7 check findings grouped by checkId', () => {
  test('Check section renders a category heading with display name + count per checkId', () => {
    const html = renderHtmlReport(
      baseReport({
        files: [
          {
            file: 'webapp/controller/A.controller.js',
            findings: [
              {
                checkId: 'missing-test-coverage',
                file: 'webapp/controller/A.controller.js',
                message: 'no unit test',
                source: 'check',
                proposedFix: null,
                explanation: 'no test exists for this controller',
              },
              {
                checkId: 'missing-test-coverage',
                file: 'webapp/controller/A.controller.js',
                message: 'no integration test',
                source: 'check',
                proposedFix: null,
                explanation: 'no opa test exists',
              },
            ],
            appliedFixes: [],
            revertedFixes: [],
          },
          {
            file: 'webapp/controller/B.controller.js',
            findings: [
              {
                checkId: 'no-direct-dom',
                file: 'webapp/controller/B.controller.js',
                message: 'querySelector usage',
                source: 'check',
                proposedFix: { newFileContent: '// fix\n' },
              },
              {
                checkId: 'missing-test-coverage',
                file: 'webapp/controller/B.controller.js',
                message: 'no test',
                source: 'check',
                proposedFix: null,
                explanation: 'no test exists',
              },
            ],
            appliedFixes: [],
            revertedFixes: [],
          },
        ],
      }),
      RENDER_OPTS,
    );
    // Category headings present, with counts.
    expect(html).toContain('Missing Test Coverage (3 findings)');
    expect(html).toContain('No Direct DOM (1 finding)');
    // Each check group is a wrapping div.
    expect(html).toContain('class="check-group"');
  });

  test('check findings are grouped first by checkId, then by file under each group', () => {
    const html = renderHtmlReport(
      baseReport({
        files: [
          {
            file: 'webapp/A.js',
            findings: [
              {
                checkId: 'missing-test-coverage',
                file: 'webapp/A.js',
                message: 'm',
                source: 'check',
                proposedFix: null,
                explanation: 'e',
              },
            ],
            appliedFixes: [],
            revertedFixes: [],
          },
          {
            file: 'webapp/B.js',
            findings: [
              {
                checkId: 'missing-test-coverage',
                file: 'webapp/B.js',
                message: 'm',
                source: 'check',
                proposedFix: null,
                explanation: 'e',
              },
              {
                checkId: 'no-direct-dom',
                file: 'webapp/B.js',
                message: 'd',
                source: 'check',
                proposedFix: { newFileContent: '' },
              },
            ],
            appliedFixes: [],
            revertedFixes: [],
          },
        ],
      }),
      RENDER_OPTS,
    );
    // Both files appear under the Missing Test Coverage group; B.js appears
    // again under No Direct DOM. Their order within the document reflects
    // the SEMANTIC_CHECK_IDS declaration order: no-direct-dom precedes
    // missing-test-coverage in src/types.ts.
    const noDomIdx = html.indexOf('No Direct DOM');
    const missingTestIdx = html.indexOf('Missing Test Coverage');
    expect(noDomIdx).toBeGreaterThan(-1);
    expect(missingTestIdx).toBeGreaterThan(noDomIdx);
  });

  test('empty check findings still emits the section heading + "No check findings." copy', () => {
    const html = renderHtmlReport(baseReport(), RENDER_OPTS);
    expect(html).toContain('Check Findings (LLM-driven)');
    expect(html).toContain('No check findings.');
    // No check-group wrappers render when there are no findings.
    expect(html).not.toContain('class="check-group"');
  });
});

describe('renderHtmlReport — V1.2-7 <details> open vs collapsed', () => {
  test('finding with proposedFix renders <details open> (actionable, prominent)', () => {
    const html = renderHtmlReport(
      baseReport({
        files: [
          {
            file: 'webapp/A.js',
            findings: [
              {
                checkId: 'no-direct-dom',
                file: 'webapp/A.js',
                message: 'm',
                source: 'check',
                proposedFix: { newFileContent: '// fixed\n' },
              },
            ],
            appliedFixes: [],
            revertedFixes: [],
          },
        ],
      }),
      RENDER_OPTS,
    );
    expect(html).toContain('<details open>');
    expect(html).toContain('<summary>Proposed fix (new file content)</summary>');
  });

  test('prose-only finding (proposedFix === null) renders <details> without the open attribute', () => {
    const html = renderHtmlReport(
      baseReport({
        files: [
          {
            file: 'webapp/A.js',
            findings: [
              {
                checkId: 'missing-test-coverage',
                file: 'webapp/A.js',
                message: 'no test',
                source: 'check',
                proposedFix: null,
                explanation: 'long prose explanation',
              },
            ],
            appliedFixes: [],
            revertedFixes: [],
          },
        ],
      }),
      RENDER_OPTS,
    );
    // The collapsed details for this finding must NOT have the open attribute.
    // We assert by extracting the wrapping <details ...> tag preceding the
    // "Explanation" summary and confirming it's the bare form.
    const idx = html.indexOf('<summary>Explanation</summary>');
    expect(idx).toBeGreaterThan(-1);
    const slice = html.slice(Math.max(0, idx - 60), idx);
    expect(slice).toContain('<details>');
    expect(slice).not.toContain('<details open>');
  });
});

describe('renderHtmlReport — applied / reverted fixes sections', () => {
  test('applied fixes per file are listed with check id and source badge', () => {
    const html = renderHtmlReport(
      baseReport({
        files: [
          {
            file: 'webapp/controller/Main.controller.js',
            findings: [],
            appliedFixes: [
              { checkId: 'no-direct-dom', source: 'check' },
              { checkId: 'baseline-ui5lint', source: 'baseline' },
            ],
            revertedFixes: [],
          },
        ],
      }),
      RENDER_OPTS,
    );
    expect(html).toContain('Applied Fixes');
    expect(html).toContain('<code>webapp/controller/Main.controller.js</code>');
    expect(html).toContain('no-direct-dom');
    expect(html).toContain('[check]');
    expect(html).toContain('baseline-ui5lint');
    expect(html).toContain('[baseline]');
    // No reverted entries → "None"-style empty message in the reverted section.
    expect(html).toContain('No fixes were reverted.');
  });

  test('reverted fixes include the verbatim reason text', () => {
    const html = renderHtmlReport(
      baseReport({
        files: [
          {
            file: 'webapp/controller/Main.controller.js',
            findings: [],
            appliedFixes: [],
            revertedFixes: [
              {
                checkId: 'no-direct-dom',
                source: 'check',
                reason: 'ui5lint failed after 3 attempts: unused variable',
              },
            ],
          },
        ],
      }),
      RENDER_OPTS,
    );
    expect(html).toContain('Reverted Fixes');
    expect(html).toContain('no-direct-dom');
    expect(html).toContain('ui5lint failed after 3 attempts: unused variable');
    // Applied section still renders with the "None" message.
    expect(html).toContain('No fixes were applied.');
  });
});

describe('renderHtmlReport — HTML escaping (security-critical)', () => {
  test('escapeHtml handles the five core characters', () => {
    expect(escapeHtml('<')).toBe('&lt;');
    expect(escapeHtml('>')).toBe('&gt;');
    expect(escapeHtml('&')).toBe('&amp;');
    expect(escapeHtml('"')).toBe('&quot;');
    expect(escapeHtml("'")).toBe('&#39;');
    expect(escapeHtml('plain text')).toBe('plain text');
    expect(escapeHtml('a < b && c > d')).toBe('a &lt; b &amp;&amp; c &gt; d');
  });

  test('file path, message, explanation, and reason all flow through escaping', () => {
    const html = renderHtmlReport(
      baseReport({
        files: [
          {
            file: 'webapp/<script>.js',
            findings: [
              {
                checkId: 'baseline-ui5lint',
                file: 'webapp/<script>.js',
                message: 'message with <b>html</b> & "quotes"',
                source: 'baseline',
                proposedFix: null,
                explanation: '<img src=x onerror=alert(1)>',
              },
            ],
            appliedFixes: [],
            revertedFixes: [
              {
                checkId: 'no-direct-dom',
                source: 'check',
                reason: 'reason with </script><script>alert(1)</script>',
              },
            ],
          },
        ],
      }),
      RENDER_OPTS,
    );
    // No raw injection survives anywhere.
    expect(html).not.toContain('<script>');
    expect(html).not.toContain('<img src=x');
    expect(html).not.toContain('<b>html</b>');
    // Escaped forms are present.
    expect(html).toContain('&lt;script&gt;');
    expect(html).toContain('&lt;b&gt;html&lt;/b&gt;');
    expect(html).toContain('&lt;img src=x onerror=alert(1)&gt;');
    expect(html).toContain('&amp;');
    expect(html).toContain('&quot;quotes&quot;');
  });

  test('proposedFix newFileContent is HTML-escaped before being embedded in <pre><code>', () => {
    const html = renderHtmlReport(
      baseReport({
        files: [
          {
            file: 'webapp/Main.js',
            findings: [
              {
                checkId: 'no-direct-dom',
                file: 'webapp/Main.js',
                message: 'has fix',
                source: 'check',
                proposedFix: {
                  newFileContent: 'if (a < b && c > d) { html = "<div>"; }',
                },
              },
            ],
            appliedFixes: [],
            revertedFixes: [],
          },
        ],
      }),
      RENDER_OPTS,
    );
    expect(html).not.toContain('<div>"');
    expect(html).toContain('a &lt; b &amp;&amp; c &gt; d');
    expect(html).toContain('&lt;div&gt;');
  });
});

describe('formatTimestamp — V1.2-7 humanization', () => {
  test('produces a human-readable string with month name, year, and "(local time)" suffix', () => {
    const out = formatTimestamp('2026-05-18T10:00:00.000Z');
    expect(out).toContain('May 2026');
    expect(out).toContain('(local time)');
    // Raw ISO must not survive.
    expect(out).not.toContain('2026-05-18T10:00:00.000Z');
    expect(out).not.toContain('T10:00');
  });

  test('falls back to the raw input when the value is not a valid date', () => {
    expect(formatTimestamp('not a date')).toBe('not a date');
  });
});

describe('formatDuration — V1.2-7 humanization', () => {
  test('sub-second runs render as milliseconds', () => {
    expect(formatDuration(0)).toBe('0 ms');
    expect(formatDuration(750)).toBe('750 ms');
  });

  test('sub-minute runs render as whole seconds', () => {
    expect(formatDuration(1000)).toBe('1 sec');
    expect(formatDuration(45000)).toBe('45 sec');
    // Rounds to nearest whole second.
    expect(formatDuration(45500)).toBe('46 sec');
  });

  test('minute-plus runs render as "X min Y sec"', () => {
    expect(formatDuration(60000)).toBe('1 min 0 sec');
    expect(formatDuration(72000)).toBe('1 min 12 sec');
    expect(formatDuration(18 * 60_000 + 32_000)).toBe('18 min 32 sec');
  });
});

describe('writeHtmlReport — fs lifecycle', () => {
  let dir: string;

  beforeEach(async () => {
    dir = await mkdtemp(join(tmpdir(), 'sapui5-html-'));
  });

  afterEach(async () => {
    await rm(dir, { recursive: true, force: true });
  });

  test('writes report.html next to report.json under .sapui5-validator/', async () => {
    const report = baseReport();
    const target = await writeHtmlReport(dir, report);
    expect(target).toBe(join(dir, '.sapui5-validator', REPORT_HTML_FILE));
    const content = await readFile(target, 'utf8');
    expect(content.startsWith('<!DOCTYPE html>')).toBe(true);
    // Content of the file matches the renderer's output (modulo the
    // version, which writeHtmlReport pulls from package.json).
    expect(content).toContain('<title>');
    expect(content).toContain('SAPUI5 Validator Report');
  });
});
